#document settings
title: Department of Labor Case Study
description: Lowering the Barrier to Entry to Government Data By Making It Accessible To Developers of all Skill Levels
url: http://gbinal.github.com/Labor_OpenData_CaseStudy
repo_url: https://github.com/gbinal/Labor_OpenData_CaseStudy

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true